// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDe9RhDXDxopFhfIk1Fcw28yMH-ZEuEWs',
    appId: '1:712784786179:web:cd29d1dabb2176d2292f36',
    messagingSenderId: '712784786179',
    projectId: 'telu-adventure-77586',
    authDomain: 'telu-adventure-77586.firebaseapp.com',
    storageBucket: 'telu-adventure-77586.appspot.com',
    measurementId: 'G-TKZVJTSD02',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoY79klX0t8BYqNd8X0a8nLvaszEvatLY',
    appId: '1:712784786179:android:903daab882ee6616292f36',
    messagingSenderId: '712784786179',
    projectId: 'telu-adventure-77586',
    storageBucket: 'telu-adventure-77586.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpW-jFCO1U13hguPneOi_xcNn2YdflNlM',
    appId: '1:712784786179:ios:46534bd006191418292f36',
    messagingSenderId: '712784786179',
    projectId: 'telu-adventure-77586',
    storageBucket: 'telu-adventure-77586.appspot.com',
    iosBundleId: 'com.example.teluAdventure',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpW-jFCO1U13hguPneOi_xcNn2YdflNlM',
    appId: '1:712784786179:ios:4811b4e7c6128641292f36',
    messagingSenderId: '712784786179',
    projectId: 'telu-adventure-77586',
    storageBucket: 'telu-adventure-77586.appspot.com',
    iosBundleId: 'com.example.teluAdventure.RunnerTests',
  );
}
